spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-web-client,config-client
      username: spring_cloud_user
      # springCloudPwd
      password: 25843bd8fbc33ca3beff53a3f0e45b9796499d81421fee0f41125d149417adc4

