version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-postgres}


  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "8081:8080"
    restart: always
    command: start
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KEYCLOAK_LOGLEVEL=DEBUG"
      - "JAVA_OPTS=-Djboss.http.port=8081"
      - "DB_URL='jdbc:postgresql://postgres:5432/postgresql?ssl=allow'"
      - "DB=keycloak"
      - "DB_SCHEMA=keycloak"
      - "DB_USERNAME=keycloak"
      - "DB_PASSWORD=keycloak"
      - "KC_PROXY_ADDRESS_FORWARDING=true"
      - "KC_HOSTNAME_STRICT=false"
      - "KC_PROXY=edge"
      - "KC_HTTP_ENABLED=true"
      - "KC_HOSTNAME_STRICT_HTTPS=false"
    depends_on:
      - postgresql
    networks:
      - ${GLOBAL_NETWORK:-postgresql}